/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;

import jacamoide.xtext.jcm.ui.outline.JcmOutlineTreeProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JcmUiModule extends AbstractJcmUiModule {

	public JcmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	    return JcmOutlineTreeProvider.class;
	}
}
