/*
 * generated by Xtext
 */
package jacamoide.xtext.jcm.ui;

import jacamoide.xtext.jcm.ui.outline.JcmOutlineTreeProvider;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JcmUiModule extends jacamoide.xtext.jcm.ui.AbstractJcmUiModule {
	public JcmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	    return JcmOutlineTreeProvider.class;
	}
}
