/*
* generated by Xtext
*/
package jacamoide.xtext.jcm.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractJcmJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(jacamoide.xtext.jcm.jcm.JcmPackage.eINSTANCE);
		return result;
	}

}
