/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class JcmProposalProvider extends AbstractJcmProposalProvider {
}
