/*
* generated by Xtext
*/
package jacamoide.xtext.jcm.ui.contentassist;

import jacamoide.xtext.jcm.ui.contentassist.AbstractJcmProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JcmProposalProvider extends AbstractJcmProposalProvider {

}
