/*
* generated by Xtext
*/
package jacamoide.xtext.jcm.ui.labeling;

import jacamoide.xtext.jcm.jcm.Agent;
import jacamoide.xtext.jcm.jcm.DAslPath;
import jacamoide.xtext.jcm.jcm.DClassPath;
import jacamoide.xtext.jcm.jcm.DNode;
import jacamoide.xtext.jcm.jcm.DPlatform;
import jacamoide.xtext.jcm.jcm.OAgents;
import jacamoide.xtext.jcm.jcm.ONode;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider; 
 
import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class JcmLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public JcmLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	public String text(Object element) {
		if (element instanceof Agent){
			return ((Agent) element).getName();
		} else if (element instanceof OAgents) {
			return "agents";
		} else if (element instanceof DClassPath) {
			return "class-path";
		} else if (element instanceof DAslPath) {
			return "asl-path";
		} else if (element instanceof DPlatform) {
			return "platform";
		}
		return (String) super.text(element);
	}
/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
}
