/*
 * generated by Xtext
 */
package jacamoide.xtext.jcm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jacamoide.xtext.jcm.ui.internal.JcmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JcmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JcmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JcmActivator.getInstance().getInjector(JcmActivator.JACAMOIDE_XTEXT_JCM_JCM);
	}
	
}
