/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJcmScopeProvider extends DelegatingScopeProvider {
}
