/*
 * generated by Xtext
 */
package jacamoide.xtext.jcm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JcmRuntimeModule extends jacamoide.xtext.jcm.AbstractJcmRuntimeModule {

}
