/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JcmStandaloneSetup extends JcmStandaloneSetupGenerated {

	public static void doSetup() {
		new JcmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
