/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JcmAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("jacamoide/xtext/jcm/parser/antlr/internal/InternalJcm.tokens");
	}
}
