/*
* generated by Xtext
*/
package jacamoide.xtext.jcm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JcmAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("jacamoide/xtext/jcm/parser/antlr/internal/InternalJcm.tokens");
	}
}
