/*
* generated by Xtext
*/
package jacamoide.xtext.jcm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jacamoide.xtext.jcm.services.JcmGrammarAccess;

public class JcmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JcmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT");
	}
	
	@Override
	protected jacamoide.xtext.jcm.parser.antlr.internal.InternalJcmParser createParser(XtextTokenStream stream) {
		return new jacamoide.xtext.jcm.parser.antlr.internal.InternalJcmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JcmModel";
	}
	
	public JcmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JcmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
