/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.parser.antlr;

import com.google.inject.Inject;
import jacamoide.xtext.jcm.parser.antlr.internal.InternalJcmParser;
import jacamoide.xtext.jcm.services.JcmGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JcmParser extends AbstractAntlrParser {

	@Inject
	private JcmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT");
	}
	

	@Override
	protected InternalJcmParser createParser(XtextTokenStream stream) {
		return new InternalJcmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JcmModel";
	}

	public JcmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JcmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
