/**
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.jcm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Artifact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Artifact#getName <em>Name</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Artifact#getClassDef <em>Class Def</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Artifact#getAgentNS <em>Agent NS</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Artifact#getAgent <em>Agent</em>}</li>
 * </ul>
 *
 * @see jacamoide.xtext.jcm.jcm.JcmPackage#getArtifact()
 * @model
 * @generated
 */
public interface Artifact extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getArtifact_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.Artifact#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Class Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Def</em>' containment reference.
   * @see #setClassDef(ClassDef)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getArtifact_ClassDef()
   * @model containment="true"
   * @generated
   */
  ClassDef getClassDef();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.Artifact#getClassDef <em>Class Def</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Def</em>' containment reference.
   * @see #getClassDef()
   * @generated
   */
  void setClassDef(ClassDef value);

  /**
   * Returns the value of the '<em><b>Agent NS</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent NS</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getArtifact_AgentNS()
   * @model unique="false"
   * @generated
   */
  EList<String> getAgentNS();

  /**
   * Returns the value of the '<em><b>Agent</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getArtifact_Agent()
   * @model unique="false"
   * @generated
   */
  EList<String> getAgent();

} // Artifact
