/**
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.jcm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DOrg Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jacamoide.xtext.jcm.jcm.DOrgPath#getOrgPath <em>Org Path</em>}</li>
 * </ul>
 *
 * @see jacamoide.xtext.jcm.jcm.JcmPackage#getDOrgPath()
 * @model
 * @generated
 */
public interface DOrgPath extends EObject
{
  /**
   * Returns the value of the '<em><b>Org Path</b></em>' containment reference list.
   * The list contents are of type {@link jacamoide.xtext.jcm.jcm.FileName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Org Path</em>' containment reference list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getDOrgPath_OrgPath()
   * @model containment="true"
   * @generated
   */
  EList<FileName> getOrgPath();

} // DOrgPath
