/**
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.jcm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DUses</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jacamoide.xtext.jcm.jcm.DUses#getFileName <em>File Name</em>}</li>
 * </ul>
 *
 * @see jacamoide.xtext.jcm.jcm.JcmPackage#getDUses()
 * @model
 * @generated
 */
public interface DUses extends EObject
{
  /**
   * Returns the value of the '<em><b>File Name</b></em>' containment reference list.
   * The list contents are of type {@link jacamoide.xtext.jcm.jcm.FileName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Name</em>' containment reference list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getDUses_FileName()
   * @model containment="true"
   * @generated
   */
  EList<FileName> getFileName();

} // DUses
