/**
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.jcm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Institution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getName <em>Name</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getFileName <em>File Name</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getWsNames <em>Ws Names</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getOther <em>Other</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getString <em>String</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getVal <em>Val</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getLiteral <em>Literal</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.Institution#getVal_real <em>Val real</em>}</li>
 * </ul>
 *
 * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution()
 * @model
 * @generated
 */
public interface Institution extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.Institution#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>File Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Name</em>' containment reference.
   * @see #setFileName(OFileName)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_FileName()
   * @model containment="true"
   * @generated
   */
  OFileName getFileName();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.Institution#getFileName <em>File Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File Name</em>' containment reference.
   * @see #getFileName()
   * @generated
   */
  void setFileName(OFileName value);

  /**
   * Returns the value of the '<em><b>Ws Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ws Names</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_WsNames()
   * @model unique="false"
   * @generated
   */
  EList<String> getWsNames();

  /**
   * Returns the value of the '<em><b>Other</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_Other()
   * @model unique="false"
   * @generated
   */
  EList<String> getOther();

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_String()
   * @model unique="false"
   * @generated
   */
  EList<String> getString();

  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_Val()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getVal();

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference list.
   * The list contents are of type {@link jacamoide.xtext.jcm.jcm.Literal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_Literal()
   * @model containment="true"
   * @generated
   */
  EList<Literal> getLiteral();

  /**
   * Returns the value of the '<em><b>Val real</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Double}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val real</em>' attribute list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getInstitution_Val_real()
   * @model unique="false"
   * @generated
   */
  EList<Double> getVal_real();

} // Institution
