/**
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.jcm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jacamoide.xtext.jcm.jcm.List#getTerm <em>Term</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.List#getVar <em>Var</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.List#getUnnamedvar <em>Unnamedvar</em>}</li>
 *   <li>{@link jacamoide.xtext.jcm.jcm.List#getList <em>List</em>}</li>
 * </ul>
 *
 * @see jacamoide.xtext.jcm.jcm.JcmPackage#getList()
 * @model
 * @generated
 */
public interface List extends EObject
{
  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference list.
   * The list contents are of type {@link jacamoide.xtext.jcm.jcm.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference list.
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getList_Term()
   * @model containment="true"
   * @generated
   */
  EList<Term> getTerm();

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getList_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.List#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Unnamedvar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unnamedvar</em>' attribute.
   * @see #setUnnamedvar(String)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getList_Unnamedvar()
   * @model
   * @generated
   */
  String getUnnamedvar();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.List#getUnnamedvar <em>Unnamedvar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unnamedvar</em>' attribute.
   * @see #getUnnamedvar()
   * @generated
   */
  void setUnnamedvar(String value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(List)
   * @see jacamoide.xtext.jcm.jcm.JcmPackage#getList_List()
   * @model containment="true"
   * @generated
   */
  List getList();

  /**
   * Sets the value of the '{@link jacamoide.xtext.jcm.jcm.List#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(List value);

} // List
