/*
 * generated by Xtext 2.23.0
 */
package jacamoide.xtext.jcm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jacamoide.xtext.jcm.JcmRuntimeModule;
import jacamoide.xtext.jcm.JcmStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JcmIdeSetup extends JcmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JcmRuntimeModule(), new JcmIdeModule()));
	}
	
}
